language: node_js
node_js:
- 11.8.0
install: npm
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'thedevelopark.com'
  skip_cleanup: true
  acl: public_read
  local_dir: public